### ISSUE TITLE
AlarmManager.setRepeating not works on idle

### ISSUE THREAD

**Issue by osmankoc** [comoser/rn-background-location#10]
Hi David,
It's a great tutorial and sample code. Thanks a lot. But this is the situation. 

My app needs to track location even phone is idle. But AlarmManager.Setrepeating not works when phone is in idle state. When user wakes the phone missed repetitions fires on once.

For example i set the interval 3 minutes. The phone is idle for 15 minutes, so is  the alarmmanager. After that i wake up the phone (ie by pressing home button) after 15 minutes alarmmanager fires 5 times and all of them give me the same last location (where i am located after 15 minutes). so i can't track the locations while the phone is idle.

do you have any suggestions?

**Comment by HeinXtet** [comment]
setExactAndAllowWhileIdle() how about these method instead of setRepeating() ?

**Comment by HeinXtet** [comment]
<img width="1689" alt="image" src="https://user-images.githubusercontent.com/35194626/93492728-20f71980-f931-11ea-9b54-1ad99ef5f099.png">

It working now on the background state or idle state of the app. Tested device One Plus 7T Pro and android version 10.

**Comment by comoser** [comment]
@HeinXtet thank you so much for your support here. Indeed there may be some faults with the specific code as I'm not maintaining it regularly, instead I wanted to provide the basis and the logic to solve the problem at hands.

Thank you for these updates 👍
