### ISSUE TITLE
Background state problem

### ISSUE THREAD

**Issue by DeevD** [comoser/rn-background-location#11]
Location is update when application is going to background but app re-open or going to foreground previous locations are suddenly updated.

Device - One Plus 7T Pro
android version - 10

**Comment by HeinXtet** [comment]
<img width="1689" alt="image" src="https://user-images.githubusercontent.com/35194626/93492808-3ff5ab80-f931-11ea-805b-2b1c13415708.png">

Solved with setExactAndAllowWhileIdle() method instead of setRepeating()
