### ISSUE TITLE
Foreground Notification Issue

### ISSUE THREAD

**Issue by ilkerkesici** [comoser/rn-background-location#2]
Hi, how can i get location without notification? or How can show notification only getting location time? For example per 10 minutes.

**Comment by comoser** [comment]
@ilkerkesici If I understood right, you want to know if you can have the background location active without the Foreground Notification always being there right?

For this question, the answer is: you can't. It is a requirement now for Android apps to use this if you want to have an active background service to run on your smartphone.

For the second part, I think you are asking how can you change the interval that you are getting the location updates. Am I right on this?

If so, you can change just this constant: 
`public static final int LOCATION_UPDATE_INTERVAL = 60000;` on the `LocationForegroundService.java` file

I hope this helped!

**Comment by ilkerkesici** [comment]
Thank you for your answer. I want to say that I want to take location per
15 minutes then I make 60000 * 15 LOCATION_TIME_INTERVAL. It is woked, but
I don’t show notofication always and continuously. May be it could showed
per 15 minutes. Are there any way to not show notification always? And the
notification cannot close by hand? I don’t want to show the notification
always to users. Can I do that?

5 Şub 2020 Çar, saat 18:24 tarihinde David Alecrim <notifications@github.com>
şunu yazdı:

**Comment by comoser** [comment]
@ilkerkesici There is no way for you in Android nowadays to do background work without showing a permanent notification to the user.
You must ALWAYS show it to the user, and the user CANNOT dismiss it. If you don't show it to the user, you cannot do background work when you want.

There are other API's that you can use for this without showing a permanent notification to the user, but it requires a more recent version of the Android SDK, and it doesn't support legacy apps.

If you use these other Job APIs you can do background work, but you don't control exactly when you do it. The OS does automatic management for when to launch your background jobs. So, it really depends on your needs for your project.

With this solution you can have full control of your background operations if you show the notification to the user always.

If you choose to use a different API, then you lose a bit of control on your background job, but you don't have to show a permanent notification to the user.

Hope I cleared your doubts.

**Comment by ilkerkesici** [comment]
Thank you so much for your answer David. You said
different API, what are the names of theese API’s? Can you tell me? How can
I search?

5 Şub 2020 Çar, saat 20:57 tarihinde David Alecrim <notifications@github.com>
şunu yazdı:

**Comment by comoser** [comment]
@ilkerkesici This is actually explained in the article that follows this repository https://medium.com/xgeeks/react-native-background-location-5602205ec795.

If you have a recent min SDK with Android X dependencies in your mobile application, then you can use `WorkManager API`.

If for some reason, you can't use the `WorkManager API`, you can try a solution with the `JobScheduler API`.

**Comment by ilkerkesici** [comment]
Thank you David

6 Şub 2020 Per, saat 13:22 tarihinde David Alecrim <notifications@github.com>
şunu yazdı:

**Comment by comoser** [comment]
Closing this hoping you have what you need :)

**Comment by ilkerkesici** [comment]
Hi, can I ask something? I have a little bit idea about native Android coding. I send ReadableMap some data from JS side to LocationModule.java -> startBackgroundLocation(). I want to request my API  when I take location on background using ReadableMap data. How can I do that? Can you help me, please?

**Comment by comoser** [comment]
> Hi, can I ask something? I have a little bit idea about native Android coding. I send ReadableMap some data from JS side to LocationModule.java -> startBackgroundLocation(). I want to request my API when I take location on background using ReadableMap data. How can I do that? Can you help me, please?

@ilkerkesici for this you need to understand how React native works internally. I will not go into great detail, but basically you have 3 parts.
The first one is you SPA in javascript. The second is the native Android part. The third is a bridge connecting these 2 parts.

This bridge is special, and it can only carry certain types of information. When you want to transport more complex data from part 1 to part 2 or vice versa, you need to use either a`ReadableMap` or a `WritableMap`.

If you want to send data from the native side to the js side when you get a location, you can do this with a listener. If you go to react docs, you can see how to setup this.
Tou basically pass a callback from the js side to the native side that is called when you get this data.

The data is fetched in a listener in the native side. when you get this listener called, you can call the callback passed from the js side with the correct data

**Comment by ilkerkesici** [comment]
Thank you David, I understood. Have a nice day!

6 Şub 2020 Per, saat 20:41 tarihinde David Alecrim <notifications@github.com>
şunu yazdı:
