### ISSUE TITLE
How send location less than 1 minute

### ISSUE THREAD

**Issue by chernandezq** [comoser/rn-background-location#4]
Hi, i need send the location less than 1 minute, I am using 

    public int onStartCommand(Intent intent, int flags, int startId) {
        createNotificationChannel();
        startForeground(NOTIFICATION_ID, createNotification());

        createLocationPendingIntent();
        mAlarmManager.setInexactRepeating(AlarmManager.RTC_WAKEUP, SystemClock.elapsedRealtime(), 15000, mLocationBackgroundServicePendingIntent);

        return START_NOT_STICKY;
    }

But dont work, Send location every  minute, any solution?
Thanks

**Comment by comoser** [comment]
@chernandezq I believe what you are asking is answered in [Issue #2](https://github.com/comoser/rn-background-location/issues/2)

You need to update the `public static final int LOCATION_UPDATE_INTERVAL = 60000;` to 1 minute.

Take into account that in Android you are not allowed to query the location on intervals lower than 1 minute. It is simply not possible. You can actually put a value lower than 1 minute, but Android will totally ignore that and set the value for 1 minute if you do this

**Comment by comoser** [comment]
Marking this as closed as I believe the explanation above clears the problem
