### ISSUE TITLE
Your solution is really awesome man. can I update the location every 10 seconds

### ISSUE THREAD

**Issue by byteab** [comoser/rn-background-location#7]

**Comment by comoser** [comment]
Hi there @EhsanSarshar 

Unfortunately, the minimum update interval Android provides is 1 minute, unless it’s real time tracking, which is not the case for this solution.

You could put 1 second as desired interval, and Android would still only give you an updated gps location every 1 minute.

**Comment by byteab** [comment]
I want to take the taxi driver location every 10 seconds and send it to server. can you put some hint to help me achieve that. so If I use FusedLocation and send an event to JS side every 10 seconds can I call some async javascript callbacks base on that event. even if app is in background ?
