### ISSUE TITLE
Testing in android oppo F9 with android 8.1.0

### ISSUE THREAD

**Issue by lyseiha** [comoser/rn-background-location#8]
The background and forceground are working perfectly, but when the app got terminate the location tracker stop working as well.

Is it the problem or because of Oppo operating System?

**Comment by comoser** [comment]
> The background and forceground are working perfectly, but when the app got terminate the location tracker stop working as well.
> 
> Is it the problem or because of Oppo operating System?

When you mention `the app got terminate`, do you mean you forcefully remove it from memory in the background?

**Comment by lyseiha** [comment]
After start tracking, i swipe it up and clear the app from recent. and the tracking location also stop tracking as well. but in another phone even app killed, it still work.

**Comment by lyseiha** [comment]
Hello sir

**Comment by comoser** [comment]
> After start tracking, i swipe it up and clear the app from recent. and the tracking location also stop tracking as well. but in another phone even app killed, it still work.

This may be a different memory management behaviour present in the oppo F9. I don't have details on that system, but using a foreground service you should be safe from being removed from memory like that. If you are, maybe that specific system does not follow the same memory rules that the standard Android follows.

My suggestion would be to search for that specific system if you can do anything in the code to make the foreground service actually be unclearable
